from pathlib import Path

src=Path('app9223.html')
out=Path('app9224.html')
s=src.read_text(encoding='utf-8')

# Leva para a nota o custo/fornecedor congelados no momento da venda de mercadoria de terceiros.
old="source:c.x.source,sourceQueueId:c.x.id,sourceKey:c.x.id"
new="source:c.x.source,sourceType:c.x.sourceType||null,sourceQueueId:c.x.id,sourceKey:c.x.id,supplierId:c.x.supplierId||null,supplierName:c.x.supplierName||'',resaleProductId:c.x.resaleProductId||null,unitCost:q(c.x.unitCost),grossMargin:(c.unit-q(c.x.unitCost))*c.amount"
if old not in s:
    raise SystemExit('Trecho da nota agrupada não encontrado para incluir custo de revenda')
s=s.replace(old,new,1)

addon=r'''<!-- HLGB_V9224_RESALE_START -->
<style>
#resalePanel9224 .resale9224-kpis{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:10px;margin:12px 0}
#resalePanel9224 .resale9224-kpi{border:1px solid var(--line);border-radius:12px;padding:12px;background:#fff}
#resalePanel9224 .resale9224-kpi small{color:var(--muted);display:block}.resale9224-kpi b{font-size:19px;display:block;margin-top:4px}
#resalePanel9224 .resale9224-positive{color:#147a42}
@media(max-width:800px){#resalePanel9224 .resale9224-kpis{grid-template-columns:1fr 1fr}}
</style>
<script>
(function(){
'use strict';
const c9224=v=>{try{return structuredClone(v)}catch(e){return JSON.parse(JSON.stringify(v))}};
const q9224=v=>Math.max(0,+v||0);
const esc9224=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money9224=v=>{try{return (+v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}catch(e){return 'R$ '+(+v||0).toFixed(2)}};
const today9224=()=>new Date().toISOString().slice(0,10);
const month9224=()=>today9224().slice(0,7);
function suppliers9224(){db.suppliers=Array.isArray(db.suppliers)?db.suppliers:[];return db.suppliers}
function clients9224(){return (db.clients||[]).slice().sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'pt-BR'))}
function resaleProducts9224(){let out=[];suppliers9224().forEach(s=>(s.resaleProducts||[]).forEach(p=>out.push({supplier:s,product:p})));return out}
async function save9224(module,row){
 if(typeof cloudEnsureFreshSession==='function')await cloudEnsureFreshSession(false);
 if(typeof window.hlgbRecordSaveWithRetry!=='function')throw new Error('A gravação na nuvem não está disponível.');
 const r=await window.hlgbRecordSaveWithRetry(module,String(row.id),c9224(row),false);if(!r||r.applied!==true)throw new Error(r?.reason||'A nuvem não confirmou a alteração.');
 const arr=db[module]=Array.isArray(db[module])?db[module]:[],i=arr.findIndex(x=>String(x.id)===String(row.id)),confirmed=r.data||row;if(i>=0)arr[i]=c9224(confirmed);else arr.push(c9224(confirmed));try{localSaveOnly()}catch(e){}return confirmed;
}
function find9224(sid,pid){let s=suppliers9224().find(x=>String(x.id)===String(sid)),p=(s?.resaleProducts||[]).find(x=>String(x.id)===String(pid));return {s,p}}
function ensurePanel9224(){
 const sec=document.getElementById('fornecedores');if(!sec)return null;let box=document.getElementById('resalePanel9224');if(!box){box=document.createElement('div');box.id='resalePanel9224';box.className='panel';sec.appendChild(box)}return box;
}
function report9224(m){
 const rows=[];(db.projectionInvoices||[]).forEach(inv=>{const im=String(inv.issueDate||inv.date||'').slice(0,7);if(im!==m)return;(inv.items||[]).forEach(i=>{if(String(i.sourceType||'')!=='resale'&&String(i.source||'')!=='Revenda')return;const qty=q9224(i.qty),sale=q9224(i.unitPrice),cost=q9224(i.unitCost);rows.push({supplier:i.supplierName||'Fornecedor',product:i.productName||'Produto',qty,revenue:qty*sale,cost:qty*cost,profit:qty*(sale-cost)})})});return rows;
}
function render9224(){
 const box=ensurePanel9224();if(!box)return;const cat=resaleProducts9224(),m=document.getElementById('resaleMonth9224')?.value||month9224(),hist=report9224(m),revenue=hist.reduce((a,x)=>a+x.revenue,0),cost=hist.reduce((a,x)=>a+x.cost,0),profit=revenue-cost,margin=revenue?profit/revenue*100:0;
 const catalogRows=cat.map(({supplier:s,product:p})=>{const mg=q9224(p.salePrice)-q9224(p.costPrice),pct=q9224(p.salePrice)?mg/q9224(p.salePrice)*100:0;return `<tr><td>${esc9224(s.name||'')}</td><td><b>${esc9224(p.name||'')}</b></td><td>${esc9224(p.unit||'un.')}</td><td>${money9224(p.costPrice)}</td><td>${money9224(p.salePrice)}</td><td class="${mg>=0?'resale9224-positive':''}">${money9224(mg)} (${pct.toFixed(1).replace('.',',')}%)</td><td>${p.active===false?'<span class="badge">Pausado</span>':'<span class="badge ok">Ativo</span>'}</td><td><button class="primary" onclick="openResaleSale9224('${esc9224(s.id)}','${esc9224(p.id)}')">Lançar venda</button> <button class="secondary" onclick="editResaleProduct9224('${esc9224(s.id)}','${esc9224(p.id)}')">Editar</button> <button class="secondary" onclick="toggleResaleProduct9224('${esc9224(s.id)}','${esc9224(p.id)}')">${p.active===false?'Ativar':'Pausar'}</button></td></tr>`}).join('');
 const groups={};hist.forEach(x=>{const k=x.supplier+'|'+x.product,g=groups[k]||(groups[k]={...x,qty:0,revenue:0,cost:0,profit:0});g.qty+=x.qty;g.revenue+=x.revenue;g.cost+=x.cost;g.profit+=x.profit});
 const histRows=Object.values(groups).sort((a,b)=>b.profit-a.profit).map(x=>`<tr><td>${esc9224(x.supplier)}</td><td>${esc9224(x.product)}</td><td>${x.qty.toLocaleString('pt-BR')}</td><td>${money9224(x.revenue)}</td><td>${money9224(x.cost)}</td><td class="${x.profit>=0?'resale9224-positive':''}"><b>${money9224(x.profit)}</b></td></tr>`).join('');
 const pending=(db.noteQueue||[]).filter(x=>x?.sourceType==='resale'&&x.status!=='Faturado'&&q9224(x.remainingQty??x.qty)>0).length;
 box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap"><div><h2 style="margin:0">🛍️ Mercadorias de terceiros / Revenda</h2><div class="sub">Cadastre o custo do fornecedor e seu preço de venda. A venda vai direto para <b>Montagem de notas</b>, sem criar pedido, corte ou produção.</div></div><div class="toolbar"><button class="secondary" onclick="newSupplier()">+ Novo fornecedor</button><button class="primary" onclick="newResaleProduct9224()">+ Produto para revenda</button></div></div><div class="sub" style="margin:8px 0"><b>${pending}</b> item(ns) de revenda aguardando montagem de nota. Eles podem ser agrupados com produtos da sua própria confecção, desde que sejam do mesmo cliente.</div><div style="overflow:auto">${catalogRows?`<table><thead><tr><th>Fornecedor</th><th>Produto</th><th>Unidade</th><th>Seu custo</th><th>Preço de venda</th><th>Margem/peça</th><th>Status</th><th>Ações</th></tr></thead><tbody>${catalogRows}</tbody></table>`:'<div class="empty">Nenhuma mercadoria de terceiros cadastrada ainda.</div>'}</div><hr style="border:0;border-top:1px solid var(--line);margin:20px 0"><div class="toolbar" style="align-items:flex-end"><div class="field"><label>Histórico de lucro no mês</label><input id="resaleMonth9224" type="month" value="${esc9224(m)}" onchange="hlgbRenderResale9224()"></div></div><div class="resale9224-kpis"><div class="resale9224-kpi"><small>Venda faturada</small><b>${money9224(revenue)}</b></div><div class="resale9224-kpi"><small>Custo da mercadoria</small><b>${money9224(cost)}</b></div><div class="resale9224-kpi"><small>Lucro bruto da revenda</small><b class="${profit>=0?'resale9224-positive':''}">${money9224(profit)}</b></div><div class="resale9224-kpi"><small>Margem</small><b>${margin.toFixed(1).replace('.',',')}%</b></div></div><div style="overflow:auto">${histRows?`<table><thead><tr><th>Fornecedor</th><th>Produto</th><th>Peças</th><th>Vendas</th><th>Custo</th><th>Lucro bruto</th></tr></thead><tbody>${histRows}</tbody></table>`:'<div class="empty">Ainda não há mercadoria de terceiros faturada neste mês.</div>'}</div>`;
}
window.hlgbRenderResale9224=render9224;
window.newResaleProduct9224=function(){
 const opts=suppliers9224().map(s=>`<option value="${esc9224(s.id)}">${esc9224(s.name||'Fornecedor')}</option>`).join('');if(!opts){alert('Cadastre primeiro o fornecedor usando + Novo fornecedor.');return}
 openModal('Cadastrar produto para revenda',`<div class="grid"><div class="field"><label>Fornecedor</label><select id="resSupplier9224">${opts}</select></div><div class="field"><label>Produto</label><input id="resName9224" placeholder="Ex.: Conjunto comprado pronto"></div><div class="field"><label>Unidade</label><input id="resUnit9224" value="peça"></div><div class="field"><label>Quanto eu pago por peça</label><input id="resCost9224" type="number" min="0" step=".01"></div><div class="field"><label>Preço padrão que eu repasso</label><input id="resSale9224" type="number" min="0" step=".01"></div></div><button class="primary modalSave">☁️ Salvar produto</button>`,async()=>{const sid=document.getElementById('resSupplier9224')?.value,s=suppliers9224().find(x=>String(x.id)===String(sid)),name=document.getElementById('resName9224')?.value?.trim()||'',cost=q9224(document.getElementById('resCost9224')?.value),sale=q9224(document.getElementById('resSale9224')?.value),unit=document.getElementById('resUnit9224')?.value?.trim()||'peça';if(!s||!name)return alert('Informe fornecedor e produto.');const next=c9224(s);next.resaleProducts=Array.isArray(next.resaleProducts)?next.resaleProducts:[];next.resaleProducts.push({id:'res-'+Date.now()+'-'+Math.floor(Math.random()*999),name,unit,costPrice:cost,salePrice:sale,active:true,createdAt:new Date().toISOString()});const btn=document.querySelector('#modal .modalSave');if(btn){btn.disabled=true;btn.textContent='☁️ Salvando…'}try{await save9224('suppliers',next);closeModal();render9224()}catch(e){if(btn){btn.disabled=false;btn.textContent='Salvar produto'}alert('Não foi possível salvar na nuvem: '+(e?.message||e))}});
};
window.editResaleProduct9224=function(sid,pid){const {s,p}=find9224(sid,pid);if(!s||!p)return;openModal('Editar mercadoria de terceiros',`<div class="grid"><div class="field"><label>Fornecedor</label><input value="${esc9224(s.name||'')}" disabled></div><div class="field"><label>Produto</label><input id="resEditName9224" value="${esc9224(p.name||'')}"></div><div class="field"><label>Unidade</label><input id="resEditUnit9224" value="${esc9224(p.unit||'peça')}"></div><div class="field"><label>Custo por peça</label><input id="resEditCost9224" type="number" min="0" step=".01" value="${q9224(p.costPrice).toFixed(2)}"></div><div class="field"><label>Preço padrão de venda</label><input id="resEditSale9224" type="number" min="0" step=".01" value="${q9224(p.salePrice).toFixed(2)}"></div></div><button class="primary modalSave">☁️ Salvar alterações</button>`,async()=>{const next=c9224(s),x=(next.resaleProducts||[]).find(z=>String(z.id)===String(pid));if(!x)return;x.name=document.getElementById('resEditName9224')?.value?.trim()||x.name;x.unit=document.getElementById('resEditUnit9224')?.value?.trim()||'peça';x.costPrice=q9224(document.getElementById('resEditCost9224')?.value);x.salePrice=q9224(document.getElementById('resEditSale9224')?.value);x.updatedAt=new Date().toISOString();const btn=document.querySelector('#modal .modalSave');if(btn)btn.disabled=true;try{await save9224('suppliers',next);closeModal();render9224()}catch(e){if(btn)btn.disabled=false;alert('A alteração não foi confirmada na nuvem.')}})};
window.toggleResaleProduct9224=async function(sid,pid){const {s}=find9224(sid,pid);if(!s)return;const next=c9224(s),p=(next.resaleProducts||[]).find(x=>String(x.id)===String(pid));if(!p)return;p.active=p.active===false;try{await save9224('suppliers',next);render9224()}catch(e){alert('Não foi possível alterar o produto: '+(e?.message||e))}};
window.openResaleSale9224=function(sid,pid){const {s,p}=find9224(sid,pid);if(!s||!p||p.active===false)return;const opts=clients9224().map(c=>`<option value="${esc9224(c.id)}">${esc9224(c.name||'Cliente')}</option>`).join('');if(!opts){alert('Cadastre um cliente antes de lançar a venda.');return}openModal('Lançar mercadoria para cliente',`<div class="cards"><div class="card"><small>Fornecedor</small><strong style="font-size:17px">${esc9224(s.name||'')}</strong></div><div class="card"><small>Produto</small><strong style="font-size:17px">${esc9224(p.name||'')}</strong></div><div class="card"><small>Seu custo</small><strong>${money9224(p.costPrice)}</strong></div><div class="card"><small>Preço padrão</small><strong>${money9224(p.salePrice)}</strong></div></div><div class="grid"><div class="field"><label>Cliente</label><select id="resClient9224">${opts}</select></div><div class="field"><label>Quantidade</label><input id="resQty9224" type="number" min="1" step="1" value="1"></div><div class="field"><label>Preço de venda por peça</label><input id="resPrice9224" type="number" min="0" step=".01" value="${q9224(p.salePrice).toFixed(2)}"></div><div class="field"><label>Data</label><input id="resDate9224" type="date" value="${today9224()}"></div></div><div class="sub">Ao confirmar, esta mercadoria aparecerá em <b>Notas → Itens aguardando nota</b>. Você poderá juntar com seus produtos normais na mesma nota.</div><button class="primary modalSave">☁️ Enviar para montagem de notas</button>`,async()=>{const cid=document.getElementById('resClient9224')?.value,c=clients9224().find(x=>String(x.id)===String(cid)),qty=Math.floor(q9224(document.getElementById('resQty9224')?.value)),price=q9224(document.getElementById('resPrice9224')?.value),date=document.getElementById('resDate9224')?.value||today9224();if(!c||qty<=0)return alert('Informe cliente e quantidade.');const id='resale-'+Date.now()+'-'+Math.floor(Math.random()*999),row={id,clientId:c.id,clientName:c.name,productId:null,productName:p.name,resaleProductId:p.id,supplierId:s.id,supplierName:s.name,qty,remainingQty:qty,unitPrice:price,unitCost:q9224(p.costPrice),deliveryDate:date,source:'Revenda',sourceType:'resale',status:'Aguardando',createdAt:new Date().toISOString()};const btn=document.querySelector('#modal .modalSave');if(btn){btn.disabled=true;btn.textContent='☁️ Confirmando…'}try{await save9224('noteQueue',row);closeModal();render9224();try{window.renderNoteQueue9202?.()}catch(e){}alert(`${qty.toLocaleString('pt-BR')} peça(s) enviada(s) para a Montagem de notas de ${c.name}.`)}catch(e){if(btn){btn.disabled=false;btn.textContent='Enviar para montagem de notas'}alert('Não foi possível confirmar na nuvem: '+(e?.message||e))}})};
const oldSup9224=window.renderSuppliers;if(typeof oldSup9224==='function')window.renderSuppliers=function(){const r=oldSup9224.apply(this,arguments);setTimeout(render9224,0);return r};
const oldPage9224=window.page;if(typeof oldPage9224==='function')window.page=function(id){const r=oldPage9224.apply(this,arguments);if(String(id)==='fornecedores')setTimeout(render9224,40);return r};
function setVersion9224(){let el=document.querySelector('#appShell .logo small');if(el)el.textContent='v92.24'}
hlgbAfterLogin(()=>{setTimeout(()=>{setVersion9224();if(document.querySelector('#fornecedores.page.active'))render9224()},400);setTimeout(setVersion9224,1800)},0);
console.log('[HLGB] v92.24 revenda de mercadorias integrada à montagem de notas');
})();
</script>
<!-- HLGB_V9224_RESALE_END -->'''

pos=s.rfind('</body>')
if pos<0: raise SystemExit('Fechamento </body> não encontrado')
s=s[:pos]+addon+'\n'+s[pos:]
s=s.replace('<title>HLGB Confecções — Sistema de Gestão v92.23 Multiusuário</title>','<title>HLGB Confecções — Sistema de Gestão v92.24 Multiusuário</title>')
out.write_text(s,encoding='utf-8')
Path('abrir.html').write_text('''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Expires" content="0"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Abrindo HLGB Confecções v92.24</title><script>(function(){window.location.replace('./app9224.html?v=92.24&fresh='+Date.now())})();</script></head><body>Abrindo HLGB...</body></html>''',encoding='utf-8')
print('v92.24 preparada: revenda por fornecedor + nota agrupada + relatório mensal de margem')
