from pathlib import Path

src=Path('app9231.html')
out=Path('app9232.html')
s=src.read_text(encoding='utf-8')

# Toda a v92.31 já teve os carimbos antigos normalizados. Avança todos os carimbos visuais
# juntos para nenhum bloco legado conseguir voltar o cabeçalho para uma versão anterior.
s=s.replace('v92.31','v92.32')

addon=r'''<!-- HLGB_V9232_FACTION_WEEKLY_STATEMENT_START -->
<style>
.hlgb9232-actions{display:flex;gap:6px;flex-wrap:wrap}.hlgb9232-models{display:grid;gap:5px;min-width:230px}.hlgb9232-model{padding:6px 8px;border:1px solid #eadde4;border-radius:8px;background:#fff8fb;font-size:12px}.hlgb9232-model b{display:block;color:#5c3749}.hlgb9232-week{font-weight:900;color:#6f3f59}.hlgb9232-summary-actions{display:flex;gap:5px;flex-wrap:wrap}.hlgb9232-detail{overflow:auto}.hlgb9232-detail table{min-width:980px}.hlgb9232-week-card{border:1px solid #eadde4;border-radius:12px;padding:12px;margin:9px 0;background:#fffafb}.hlgb9232-week-head{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}
</style>
<script>
(function(){
'use strict';
const q9232=v=>Math.max(0,+v||0);
const e9232=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const m9232=v=>typeof money==='function'?money(v):q9232(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fd9232=v=>{try{return typeof fmtDate==='function'?fmtDate(v):(v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'-')}catch(_){return String(v||'-')}};
function norm9232(v){return String(v||'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function wk9232(p){
 if(p?.scheduledPaymentWeek)return String(p.scheduledPaymentWeek);
 const ds=String(p?.scheduledPaymentDate||p?.serviceFinishedAt||'').slice(0,10);if(!ds)return 'SEM-DATA';
 const d=new Date(ds+'T12:00:00'),tmp=new Date(d);tmp.setHours(0,0,0,0);tmp.setDate(tmp.getDate()+3-((tmp.getDay()+6)%7));const w1=new Date(tmp.getFullYear(),0,4);const wk=1+Math.round(((tmp-w1)/86400000-3+((w1.getDay()+6)%7))/7);return `${tmp.getFullYear()}-W${String(wk).padStart(2,'0')}`;
}
function range9232(w){
 const x=String(w||'').match(/^(\d{4})-W(\d{2})$/);if(!x)return {label:w||'Sem semana',start:'',end:''};
 const y=+x[1],n=+x[2],jan4=new Date(Date.UTC(y,0,4)),day=jan4.getUTCDay()||7,mon=new Date(jan4);mon.setUTCDate(jan4.getUTCDate()-day+1+(n-1)*7);const sun=new Date(mon);sun.setUTCDate(mon.getUTCDate()+6);
 const iso=d=>d.toISOString().slice(0,10);return {start:iso(mon),end:iso(sun),label:`${fd9232(iso(mon))} a ${fd9232(iso(sun))}`};
}
function rem9232(p){try{return typeof window.factionPaymentRemaining==='function'?Math.max(0,+window.factionPaymentRemaining(p)||0):Math.max(0,q9232(p.value)-q9232(p.travetaDiscount)-q9232(p.discountAmount)-q9232(p.paidAmount))}catch(_){return Math.max(0,q9232(p.value)-q9232(p.travetaDiscount)-q9232(p.discountAmount)-q9232(p.paidAmount))}}
function forceCalc9232(p){rem9232(p);return p}
function group9232(rows){
 const map=new Map();(rows||[]).forEach(p=>{forceCalc9232(p);const week=wk9232(p),name=String(p.factionName||'Sem facção').trim()||'Sem facção',key=norm9232(name)+'||'+week;let g=map.get(key);if(!g){g={key,name,week,items:[],pix:''};map.set(key,g)}g.items.push(p);if(!g.pix&&p.pix)g.pix=String(p.pix)});return [...map.values()].sort((a,b)=>String(b.week).localeCompare(String(a.week))||a.name.localeCompare(b.name,'pt-BR'));
}
function totals9232(g){g.items.forEach(forceCalc9232);const pieces=g.items.reduce((a,p)=>a+q9232(p.quantity),0),gross=g.items.reduce((a,p)=>a+q9232(p.value),0),trav=g.items.reduce((a,p)=>a+q9232(p.travetaDiscount),0),disc=g.items.reduce((a,p)=>a+q9232(p.discountAmount),0),paid=g.items.reduce((a,p)=>a+q9232(p.paidAmount),0),rem=g.items.reduce((a,p)=>a+rem9232(p),0);return {pieces,gross,trav,disc,paid,rem,net:Math.max(0,gross-trav-disc)}}
function status9232(g){const t=totals9232(g);if(t.rem<=.009)return 'Pago';if(t.paid>0||t.disc>0||t.trav>0)return 'Parcial';return 'Pendente'}
function periodRows9232(){
 try{if(typeof syncFactionPayments==='function')syncFactionPayments()}catch(e){}
 const start=document.getElementById('fpPeriodStart')?.value||'',end=document.getElementById('fpPeriodEnd')?.value||'';
 return (Array.isArray(db.factionPayments)?db.factionPayments:[]).filter(p=>{try{return typeof factionPaymentInPeriod==='function'?factionPaymentInPeriod(p,start,end):true}catch(_){return true}})
}
function allGroups9232(){return group9232(Array.isArray(db.factionPayments)?db.factionPayments:[])}
function visibleGroups9232(){const filter=document.getElementById('factionPaymentFilter')?.value||'';return group9232(periodRows9232()).filter(g=>!filter||status9232(g)===filter)}
function groupByKey9232(key){return allGroups9232().find(g=>g.key===key)||null}
function periodFactionGroups9232(name){const n=norm9232(name);return group9232(periodRows9232()).filter(g=>norm9232(g.name)===n)}
function modelRows9232(g,actions=true){return g.items.slice().sort((a,b)=>String(a.serviceFinishedAt||'').localeCompare(String(b.serviceFinishedAt||''))).map(p=>{forceCalc9232(p);const abat=q9232(p.travetaDiscount)+q9232(p.discountAmount);return [fd9232(p.serviceFinishedAt),e9232(p.description||'-'),q9232(p.quantity).toLocaleString('pt-BR'),m9232(p.unitPrice),m9232(p.value),q9232(p.travetaDiscount)?'- '+m9232(p.travetaDiscount):'-',q9232(p.discountAmount)?'- '+m9232(p.discountAmount):'-',m9232(Math.max(0,q9232(p.value)-abat)),m9232(p.paidAmount),m9232(rem9232(p)),`<span class="badge ${String(p.status)==='Pago'?'ok':String(p.status)==='Parcial'?'warn':''}">${e9232(p.status||'Pendente')}</span>`,actions?`<button class="secondary" onclick="closeModal();setTimeout(()=>editFactionPayment(${Number(p.id)}),30)">Editar</button>`:'']})}
function detailHtml9232(g,actions=true){const t=totals9232(g),rg=range9232(g.week);return `<div class="cards"><div class="card"><small>Semana</small><strong style="font-size:17px">${e9232(g.week)}</strong><div class="sub">${e9232(rg.label)}</div></div><div class="card"><small>Peças</small><strong>${t.pieces.toLocaleString('pt-BR')}</strong></div><div class="card"><small>Bruto</small><strong>${m9232(t.gross)}</strong></div><div class="card"><small>Líquido</small><strong>${m9232(t.net)}</strong></div><div class="card"><small>Já pago</small><strong>${m9232(t.paid)}</strong></div><div class="card"><small>Saldo</small><strong>${m9232(t.rem)}</strong></div></div><div class="sub" style="margin:8px 0"><b>PIX:</b> ${e9232(g.pix||'-')}</div><div class="hlgb9232-detail">${table(['Finalizado','Modelo / serviço','Qtd.','Preço','Bruto','Traveta','Outros abat.','Líquido','Pago','Saldo','Status',actions?'Ação':''],modelRows9232(g,actions))}</div>`}
function printDoc9232(title,body){const w=window.open('','_blank','width=1050,height=780');if(!w){alert('O navegador bloqueou a janela de impressão. Libere pop-ups para o HLGB e tente novamente.');return}w.document.open();w.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${e9232(title)}</title><style>@page{size:A4;margin:12mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#2d2429;font-size:12px;margin:0}.brand{font-size:22px;font-weight:900;color:#6f3f59;margin-bottom:3px}.muted{color:#766b71}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #6f3f59;padding-bottom:10px;margin-bottom:14px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:10px 0}.card{border:1px solid #ddd;border-radius:8px;padding:8px}.card small{display:block;color:#777}.card b{display:block;font-size:15px;margin-top:3px}table{width:100%;border-collapse:collapse;margin:8px 0 16px}th,td{border-bottom:1px solid #ddd;padding:6px 5px;text-align:left;vertical-align:top}th{background:#f5eef2;font-size:10px}.week{page-break-inside:avoid;margin:12px 0 20px}.week h2{color:#6f3f59;margin:0 0 3px;font-size:17px}.totals{font-weight:800;background:#faf5f8}.no-print{margin:12px 0;padding:9px;border:1px solid #ddd;border-radius:8px}@media print{.no-print{display:none}}</style></head><body><div class="head"><div><div class="brand">HLGB CONFECÇÕES</div><div class="muted">Demonstrativo de acerto de facção</div></div><div style="text-align:right"><b>${e9232(title)}</b><div class="muted">Gerado em ${new Date().toLocaleString('pt-BR')}</div></div></div>${body}<div class="no-print">Para gerar o PDF, escolha <b>Salvar como PDF</b> na janela de impressão.</div><script>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close();w.focus()}
function printableGroup9232(g){const t=totals9232(g),rg=range9232(g.week),rows=g.items.slice().sort((a,b)=>String(a.serviceFinishedAt||'').localeCompare(String(b.serviceFinishedAt||''))).map(p=>{forceCalc9232(p);const trav=q9232(p.travetaDiscount),disc=q9232(p.discountAmount),liq=Math.max(0,q9232(p.value)-trav-disc);return `<tr><td>${fd9232(p.serviceFinishedAt)}</td><td><b>${e9232(p.description||'-')}</b></td><td>${q9232(p.quantity).toLocaleString('pt-BR')}</td><td>${m9232(p.unitPrice)}</td><td>${m9232(p.value)}</td><td>${trav?'- '+m9232(trav):'-'}</td><td>${disc?'- '+m9232(disc):'-'}</td><td>${m9232(liq)}</td><td>${m9232(p.paidAmount)}</td><td>${m9232(rem9232(p))}</td></tr>`}).join('');return `<section class="week"><h2>${e9232(g.name)} — ${e9232(g.week)}</h2><div class="muted">${e9232(rg.label)} · PIX: ${e9232(g.pix||'-')}</div><div class="cards"><div class="card"><small>Modelos</small><b>${g.items.length}</b></div><div class="card"><small>Peças</small><b>${t.pieces.toLocaleString('pt-BR')}</b></div><div class="card"><small>Bruto</small><b>${m9232(t.gross)}</b></div><div class="card"><small>Saldo a pagar</small><b>${m9232(t.rem)}</b></div></div><table><thead><tr><th>Finalizado</th><th>Modelo / serviço</th><th>Qtd.</th><th>Preço</th><th>Bruto</th><th>Traveta</th><th>Outros abat.</th><th>Líquido</th><th>Pago</th><th>Saldo</th></tr></thead><tbody>${rows}<tr class="totals"><td colspan="2">TOTAL DA SEMANA</td><td>${t.pieces.toLocaleString('pt-BR')}</td><td>-</td><td>${m9232(t.gross)}</td><td>${t.trav?'- '+m9232(t.trav):'-'}</td><td>${t.disc?'- '+m9232(t.disc):'-'}</td><td>${m9232(t.net)}</td><td>${m9232(t.paid)}</td><td>${m9232(t.rem)}</td></tr></tbody></table></section>`}
window.hlgbFactionStatement9232=function(key){const g=groupByKey9232(key);if(!g)return;openModal('Acerto detalhado — '+e9232(g.name),`${detailHtml9232(g,true)}<div class="toolbar" style="margin-top:12px"><button class="primary" onclick='hlgbPrintFactionStatement9232(${JSON.stringify(g.key)})'>🖨️ Imprimir / salvar PDF</button><button class="secondary" onclick="closeModal()">Fechar</button></div>`,()=>true)};
window.hlgbPrintFactionStatement9232=function(key){const g=groupByKey9232(key);if(!g)return;printDoc9232(`Acerto ${g.name} — ${g.week}`,printableGroup9232(g))};
window.hlgbFactionPeriod9232=function(name){const gs=periodFactionGroups9232(name);if(!gs.length)return;const blocks=gs.map(g=>{const t=totals9232(g),rg=range9232(g.week);return `<div class="hlgb9232-week-card"><div class="hlgb9232-week-head"><div><b>${e9232(g.week)} · ${e9232(rg.label)}</b><div class="sub">${g.items.length} modelo(s) · ${t.pieces.toLocaleString('pt-BR')} peças · saldo ${m9232(t.rem)}</div></div><div class="hlgb9232-actions"><button class="secondary" onclick='closeModal();setTimeout(()=>hlgbFactionStatement9232(${JSON.stringify(g.key)}),30)'>Ver detalhado</button><button class="primary" onclick='hlgbPrintFactionStatement9232(${JSON.stringify(g.key)})'>🖨️ PDF</button></div></div></div>`}).join('');openModal('Acertos por semana — '+e9232(name),`${blocks}<div class="toolbar" style="margin-top:12px"><button class="primary" onclick='hlgbPrintFactionPeriod9232(${JSON.stringify(name)})'>🖨️ Imprimir período / PDF</button><button class="secondary" onclick="closeModal()">Fechar</button></div>`,()=>true)};
window.hlgbPrintFactionPeriod9232=function(name){const gs=periodFactionGroups9232(name);if(!gs.length)return;printDoc9232(`Acertos — ${name}`,gs.map(printableGroup9232).join(''))};
function renderSummary9232(){const host=document.getElementById('factionPaymentSummary');if(!host)return;const groups=group9232(periodRows9232()),map=new Map();groups.forEach(g=>{let x=map.get(norm9232(g.name));if(!x){x={name:g.name,pix:g.pix,groups:[],pieces:0,gross:0,paid:0,rem:0};map.set(norm9232(g.name),x)}const t=totals9232(g);x.groups.push(g);x.pieces+=t.pieces;x.gross+=t.gross;x.paid+=t.paid;x.rem+=t.rem;if(!x.pix&&g.pix)x.pix=g.pix});const rows=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')).map(x=>[e9232(x.name),x.pieces.toLocaleString('pt-BR'),m9232(x.gross),m9232(x.rem),m9232(x.paid),x.pix?e9232(x.pix):'-',`<div class="hlgb9232-summary-actions"><button class="secondary" onclick='hlgbFactionPeriod9232(${JSON.stringify(x.name)})'>📄 Ver acertos</button><button class="primary" onclick='hlgbPrintFactionPeriod9232(${JSON.stringify(x.name)})'>🖨️ PDF</button></div>`]);host.innerHTML=rows.length?table(['Facção','Peças','Total do período','Pendente','Pago','Chave PIX','Acerto'],rows):'<div class="empty">Nenhum pagamento de facção no período.</div>'}
function renderServices9232(){const host=document.getElementById('factionPaymentTable');if(!host)return;const groups=visibleGroups9232(),rows=groups.map(g=>{const t=totals9232(g),st=status9232(g),rg=range9232(g.week),models=g.items.slice().sort((a,b)=>String(a.serviceFinishedAt||'').localeCompare(String(b.serviceFinishedAt||''))).map(p=>`<div class="hlgb9232-model"><b>${e9232(p.description||'Serviço')}</b>${q9232(p.quantity).toLocaleString('pt-BR')} pç · ${m9232(p.unitPrice)}/pç · ${m9232(p.value)}</div>`).join('');return [`<span class="hlgb9232-week">${e9232(g.week)}</span><div class="sub">${e9232(rg.label)}</div>`,`<b>${e9232(g.name)}</b>`,g.pix?e9232(g.pix):'-',`<div class="hlgb9232-models">${models}</div>`,t.pieces.toLocaleString('pt-BR'),m9232(t.gross),t.trav?'- '+m9232(t.trav):'-',t.disc?'- '+m9232(t.disc):'-',m9232(t.net),m9232(t.paid),m9232(t.rem),`<span class="badge ${st==='Pago'?'ok':st==='Parcial'?'warn':''}">${st}</span>`,`<div class="hlgb9232-actions"><button class="secondary" onclick='hlgbFactionStatement9232(${JSON.stringify(g.key)})'>Detalhes</button><button class="secondary" onclick='hlgbPrintFactionStatement9232(${JSON.stringify(g.key)})'>🖨️ PDF</button>${st==='Pago'?`<button class="secondary" onclick='hlgbReopenFactionGroup9230(${JSON.stringify(g.key)})'>Reabrir</button>`:`<button class="primary" onclick='hlgbPayFactionGroup9230(${JSON.stringify(g.key)})'>Dar baixa</button>`}</div>`]});host.innerHTML=rows.length?table(['Semana','Facção','PIX','Modelos / serviços','Peças','Bruto','Traveta','Outros abat.','Líquido','Pago','Saldo','Status','Ações'],rows):'<div class="empty">Nenhum serviço encontrado.</div>'}
function render9232(){try{renderSummary9232();renderServices9232()}catch(e){console.error('[HLGB 92.32] render acertos',e)}}
const prev9232=window.renderFactionPayments;window.renderFactionPayments=function(){let r;try{r=typeof prev9232==='function'?prev9232.apply(this,arguments):undefined}catch(e){console.warn('[HLGB 92.32] render anterior',e)}setTimeout(render9232,0);return r};
function stamp9232(){try{document.title='HLGB Confecções — Sistema de Gestão v92.32 Multiusuário'}catch(e){}try{const el=document.querySelector('#appShell .logo small');if(el)el.textContent='v92.32'}catch(e){}}
if(typeof hlgbAfterLogin==='function')hlgbAfterLogin(()=>{setTimeout(()=>{stamp9232();render9232()},500)},0);setTimeout(stamp9232,900);
console.log('[HLGB] v92.32 acerto semanal detalhado, agrupado e pronto para impressão/PDF');
})();
</script>
<!-- HLGB_V9232_FACTION_WEEKLY_STATEMENT_END -->'''

pos=s.rfind('</body>')
if pos<0: raise SystemExit('</body> não encontrado')
s=s[:pos]+addon+'\n'+s[pos:]
out.write_text(s,encoding='utf-8')
Path('abrir.html').write_text('''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Expires" content="0"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Abrindo HLGB Confecções v92.32</title><script>(function(){window.location.replace('./app9232.html?v=92.32&fresh='+Date.now())})();</script></head><body>Abrindo HLGB...</body></html>''',encoding='utf-8')
print('v92.32 preparada: acertos por facção/semana agrupados, detalhados e imprimíveis/PDF.')
